repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'env/phishing_gthc/Scripts/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]